config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  devise_for :users
  get 'home/about' => 'homes#about' , as: 'about'

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
    get "search", to: "users#search"
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  
  get "search_book" => "books#search_book"
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :view_counts, dependent: :destroy
  has_many :group_users
  
  
  
  has_one_attached :profile_image
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  
  
  
   # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following
  # =======================================================================================
  
  

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end
  
  
  
  
def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:alert] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render 'users/edit'
    end  
  end
  
  
  
  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  
  end
  
  def search
    @user = User.find(params[:user_id])
    @books = @user.books 
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"#①
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end
  
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to "/users/#{current_user.id}"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_search.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr> 
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/_user_show.html.erb
    <h2>User info</h2>
      <%= image_tag user.get_profile_image(63,63) %>
      
      			<table class="table">
              <tbody>
                <tr>
                  <th>name</th><th><%= user.name %></th>
                </tr>
                <tr>
                  <th>introduction</th><th><%= user.introduction %></th>
                </tr>
                <tr>
                  <th>follows</th><th><%=link_to user.followings.count, follows_user_path(user.id) %></th>
                </tr>
                <tr>
                  <th>followers</th><th><%=link_to user.followers.count, followers_user_path(user.id) %></th>
                </tr>
              </tbody>
            </table>
            
       
            
      

app/views/users/edit.html.erb
<%= alert %>


<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

     <h2>User info</h2>
        <%= form_with model: @user do |f| %>
          
          <div class="form-group">
            <label for="inputName">Name</label></br>
            <%= f.text_field :name, autofocus: true, id:"inputName"%></br>
          </div>
          
          <div class="form-group">
            <label for="inputImage">Image</label></br>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></br> 
          </div>
          
          <div class="form-group">
            <label for="inputIntroduction">Introduction</label></br>
            <%= f.text_field :introduction, autofocus: true, id:"Introduction"%></br>
          </div>
          
          <div class="form-group">
            <%= f.submit 'Update User', class: 'btn btn-secondary' %>
          </div>
          
        <% end %>
    </div>
  </div>
</div> 

app/views/users/followers.html.erb
    <h4>Follwer User</h4>
<% if @users.exists? %>


<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><p><%= image_tag user.get_profile_image(40,40) %></p></td>
						<td><p><%= user.name %></p></td>
						<td><%= link_to "Show", user_path(user.id) %></td>
						<td></td>
						<td></td>
						<td>
							<% if current_user != user %>
					        <% if user.followed_by?(current_user) %>
					            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete, class: 'btn btn-success' %></p>
					        <% else %>
					            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: 'btn btn-success' %></p>
					        <% end %>
    					<% end %>
    				</td>
					</tr>
					<% end %>
				</tbody>
			</table>
<% else %>
      <p>ユーザーはいません</p>
<% end %>

app/views/users/follows.html.erb
<h2>Follow User</h2>
<% if @users.exists? %>


<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><p><%= image_tag user.get_profile_image(40,40) %></p></td>
						<td><p><%= user.name %></p></td>
						<td><%= link_to "Show", user_path(user.id) %></td>
						<td></td>
						<td></td>
						<td>
							<% if current_user != user %>
					        <% if user.followed_by?(current_user) %>
					            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete, class: 'btn btn-success' %></p>
					        <% else %>
					            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: 'btn btn-success' %></p>
					        <% end %>
    					<% end %>
    				</td>
					</tr>
					<% end %>
				</tbody>
			</table>

	<% else %>
      <p>ユーザーはいません</p>
    <% end %>

app/views/users/index.html.erb
  <div class="container px-5 px-sm-0">

		<div class="row">
			<div class="col-md-3">
				<%= render 'users/user_show', user: @user %>
				<%= render 'books/book_new', book: @book %>
			</div>
		
		
		
		
		
		<!--<% @users.each do |user| %>-->
		<!--	<div>-->
			  
		<!--	  <p>image：<%= image_tag user.get_profile_image(100,100) %></p>-->
		<!--	  <p>name：<%= user.name %></p>-->
			  
		<!--	  <%= link_to "Show", user_path(user.id) %>-->
		<!--	</div>-->
		<!--<% end %>-->
		
		<div class="col-md-8 offset-md-1">
		
			<h1>Users</h1>
			<div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><p><%= image_tag user.get_profile_image(40,40) %></p></td>
						<td><p><%= user.name %></p></td>
						<td><%= link_to "Show", user_path(user.id) %></td>
						<td>フォロー数:<%= user.followings.count %></td>
						<td>フォロワー数:<%= user.followers.count %></td>
						<td>
							<% if current_user != user %>
					        <% if user.followed_by?(current_user) %>
					            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete, class: 'btn btn-success' %></p>
					        <% else %>
					            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: 'btn btn-success' %></p>
					        <% end %>
    					<% end %>
    				</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			

			
		</div>
		</div>
	</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
	<!--<%= alert %>-->
<div class="container px-5 px-sm-0">

		<div class="row">
						<div class="col-md-3">
							<%= render 'users/user_show', user: @user %>
							
							
							<div class='row'>
        <% if current_user != @user %>
            <% if @user.followed_by?(current_user) %>
              <p><%=link_to "フォロー済み", user_relationships_path(@user.id), method: :delete, class: 'btn btn-success' %></p>
            <% else %>
              <p><%=link_to "フォローする", user_relationships_path(@user.id), method: :post, class: 'btn btn-success' %></p>
            <% end %>
            
        <% if (current_user.followed_by?(@user)) && (@user.followed_by?(current_user))  %>
          <% if @isRoom == true %>
            <%= link_to 'チャットへ', room_path(@roomId), class:"btn btn-primary btn-lg user-show-chat" %>
          <% else %>
            <%= form_with model: @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, value: @user.id %>
              <% end %>
              <%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
            <% end %>
          <% end %>
          <% end %>
        <% end %>
        
        
    	    <%= link_to edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block' do %>
    	      <i class="fas fa-user-cog"></i>
    	   
          <% end %>	
      </div>
							<%= render 'books/book_new', book: @book %>
						</div>
			

					<div class="col-md-8 offset-md-1">
  								<h2>Books</h2>
								  		<table class="table table-hover table-inverse">
								  			<thead>
											    <tr>
											      <th></th>
											      <th>Title</th>
											      <th>Opinion</th>
											      <th>Category</th>
											      <th colspan="3"></th>
											    </tr>
											</thead>  
								  		  <tbody>
								  		  	<% @books.each do |book| %>
								  		  	<tr>
									          <td><%= link_to user_path(book.user) do %>
									          			<%= image_tag book.user.get_profile_image(40,40) %></td>
									          	  <% end %>
									          <td><%= link_to book_path(book.id) do %> 
				          							<%= book.title %>
				        						  <% end %>
				        					  </td>
									          <td><%= book.body %></td>
									          <td><%= book.category%></td>
									          
									          <td>
									          	<% if book.favorited_by?(current_user) %>
														    <p>
														      <%= link_to book_favorites_path(book.id), class: 'post-btn', method: :delete do %>
														        <i class="fa-solid fa-heart" style="color: red;"></i>
														        <span class='post-btn-text' style="color: red;"><%= book.favorites.count %></span>
														        
														      <% end %>
														    </p>
														 <% else %>
														    <p>
														      <%= link_to book_favorites_path(book.id), class: 'post-btn', method: :post do %>
														        <i class="fa-solid fa-heart" style="color: blue;"></i>
														        <span class='post-btn-text' style="color: blue;"><%= book.favorites.count %></span>
														        
														      <% end %>
														    </p>
												<% end %>
				        						</td>
			  			
						    <td><p>コメント数：<%= book.book_comments.count %></p></td>
									        </tr>
									       <% end %> 
								      	</tbody>
								      </table>
								      <table class="table table-bordered">
								      	
							<div class = "table_width">	      	
					    <thead>
					     <tr>
					      <th>今日の投稿数</th>
					      <th>前日の投稿数</th>
					      <th>前日比</th>
					     </tr>
					    </thead>
					    <tbody>
					     <tr>
					     　<td><%= @today_book.count %></td>
					     　<td><%= @yesterday_book.count %></td>
					     　<td>
					       <% if @yesterday_book.count == 0 %>
					        前日の投稿はありません
					       <% else %>
					       　<% @the_day_before =   @today_book.count / @yesterday_book.count.to_f  %>
					       　<%= (@the_day_before * 100).round %>%
					       <% end %>
					      </td>
					     </tr>
					    </tbody>
					   </table>
					   <table class="table table-bordered">
						  <thead>
						  <tr>
						   <th>今週の投稿</th>
						   <th>先週の投稿</th>
						   <th>前週比</th>
						  </tr>
						  </thead>
						   <tbody>
						    <tr>
						     <td><%= @this_week_book.count %></td>
						     <td><%= @last_week_book.count %></td>
						     <% if @last_week_book.count == 0 %>
						     <td>先週の投稿はなし</td>
						     <% else %>
						       　<td><% @the_week_before =   @this_week_book.count / @last_week_book.count.to_f  %>
						       　<%= (@the_week_before * 100).round %>%</td>
						     <% end %>
						     </tr>
						   </tbody>
						  </table>
					   </div>
					   
					</div>
					
					
				
		</div>		
</div>