config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  devise_for :users
  get 'home/about' => 'homes#about' , as: 'about'

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
    get "search", to: "users#search"
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  
  get "search_book" => "books#search_book"
  
end

app/models/book.rb
class Book < ApplicationRecord

	validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	has_many :favorited_users, through: :favorites, source: :user

	has_many :view_counts, dependent: :destroy
	
	has_many :book_tags,dependent: :destroy
  has_many :tags,through: :book_tags

	scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
	scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
	scope :created_2days, -> { where(created_at: 2.days.ago.all_day) }
    scope :created_3days, -> { where(created_at: 3.days.ago.all_day) }
    scope :created_4days, -> { where(created_at: 4.days.ago.all_day) }
    scope :created_5days, -> { where(created_at: 5.days.ago.all_day) }
    scope :created_6days, -> { where(created_at: 6.days.ago.all_day) }

	scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
    scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}
  
  def self.search(search_word)
    Book.where(['category LIKE ?', "%#{search_word}%"])
	end

	def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def index
    if params[:latest]
     @books = Book.latest
    elsif params[:old]
     @books = Book.old
    elsif params[:star_count]
     @books = Book.star_count
    else
     @books = Book.includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}
    end
    @book = Book.new
    @user = current_user
    
    @books_create = @user.books
    @today_book = @books_create.created_today
    @yesterday_book = @books_create.created_yesterday
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:alert] = "You have created book successfully."
      redirect_to book_path(@book.id)

    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
  end




  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:alert] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render 'books/edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])  # データ（レコード）を1件取得
    @book.destroy  # データ（レコード）を削除
    # flash[:alert] = "Book was successfully destroyed"
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end
  
  def search_book
     @book = Book.new
     @user = current_user
     @books = Book.search(params[:keyword])
  end

  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body, :star, :category)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_new.html.erb
    <h2 class="mt-3">New book</h2>
    
    
    
    <%= form_with model: book, url: '/books', method: :post do |f| %>
    
      <div class="form-group">
        <label for="book_title">Title</label></br>
          <%= f.text_field :title, class: 'form-control book_title' %>
    	</div>
    	
    	
      <div class="form-group">
        <label for="book_opinion">Opinion</label></br>
          <%= f.text_area :body, class: 'form-control book_body' %>
    	</div>
    	
    	<div class="form-group">
        <label for="book_opinion">Category</label></br>
          <%= f.text_field :category, class: 'form-control book_category' %>
    	</div>
    	
    	<div class="form-group row" id="star">
          <%= f.label :star, '評価', class: 'col-md-3 col-form-label' %>
          <%= f.hidden_field :star, id: :review_star %>
      　</div>
    	
    	<div class="form-group">
        <br><%= f.submit 'Create Book', class: 'btn btn-sm btn-success' %></br>
      </div>
      
       
        <script>
        　$('#star').empty();
          $('#star').raty({
            size     : 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
         　　scoreName: 'book[star]',　
            half: true,
        });
        </script>
    <% end %>
    

app/views/books/edit.html.erb
<%= alert %>

<% if @book.errors.any? %>
          <%= @book.errors.count %>error prohibited this book from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        
        
        
        <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
        
          <div class="form-group">
            <label for="book_title">Title</label></br>
            <%= f.text_field :title %>
          </div>
          
          <div class="form-group">
            <label for="book_opinion">Opinion</label></br>
            <%= f.text_area :body %>
          </div>
          
          <div class="form-group">
            <%= f.submit 'Update Book', class: 'btn btn-sm btn-success' %>
          </div>
          
        <% end %>
        
        
        <span>
            <%= link_to "Show", book_path(@book.id)%>
        </span>
        |
        <span>
            <%= link_to "Back", "/books" %>
        </span>
        
        
        
        
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
				  <%= @book.errors.count %>error prohibited this book from being saved:
				  <ul>
				    <% @book.errors.full_messages.each do |message| %>
				      <li><%= message %></li>
				    <% end %>
				  </ul>
			<% end %>
<div class="container px-5 px-sm-0">

		<div class="row">



			<div class="col-md-3">
				<%= render 'users/user_show', user: @user %>
				<%= render 'books/book_new', book: @book %>
			</div>


		<div class="col-md-8 offset-md-1">

			<h1>Books</h1>
			<p>
        <%= link_to '新しい順', books_path(latest: "true") %>
       |<%= link_to '古い順', books_path(old: "true") %>
       |<%= link_to '評価の高い順', books_path(star_count: "true") %>
      </p>

			<table class="table table-hover table-inverse">
				<thead>
					<tr>
					  <th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th>Category</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
					  <td><%= link_to user_path(book.user) do %>
					  				<%= image_tag book.user.get_profile_image(40,40) %>
					  		<% end %>
					  </td>

						<td><%= link_to book_path(book.id) do %>
				          <%= book.title %>
				        <% end %>
				     </td>
						<td><%= book.body %></td>
						<td>
							<%= link_to book.category, search_book_path(keyword: book.category) %>
						</td>
						<td>
									          	<% if book.favorited_by?(current_user) %>
														    <p>
														      <%= link_to book_favorites_path(book.id), class: 'post-btn', method: :delete do %>
														        <i class="fa-solid fa-heart" style="color: red;"></i>
														        <span class='post-btn-text' style="color: red;"><%= book.favorites.count %></span>

														      <% end %>
														    </p>
														    <% else %>
														    <p>
														      <%= link_to book_favorites_path(book.id), class: 'post-btn', method: :post do %>
														        <i class="fa-solid fa-heart" style="color: blue;"></i>
														        <span class='post-btn-text' style="color: blue;"><%= book.favorites.count %></span>

														      <% end %>
														    </p>
													    <% end %>
				        </td>
				        <td>
				          <div id="star-rate<%= book.id%>"> </div>    
				          <script>
				            $('#star-rate<%= book.id %>').empty();
				            $('#star-rate<%= book.id%>').raty({
				              size      : 36,
				              starOff   : '<%= asset_path('star-off.png') %>',
				              starOn    : '<%= asset_path('star-on.png') %>',
				              starHalf  : '<%= asset_path('star-half.png') %>',
				              half      : true,
				              readOnly: true,
				              score: <%= book.star %>,
				            });
				          </script>
				          
								</td>
						    <td><p>コメント数：<%= book.book_comments.count %></p></td>
						    <td><%= l book.created_at %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

<table class="table table-bordered">
   <thead>
    <tr>
     <th>６日前</th>
     <th>5日前</th>
     <th>4日前</th>
     <th>3日前</th>
     <th>２日前</th>
     <th>昨日</th>
     <th>今日</th>
    </tr>
   </thead>
   <tbody>
    <tr>
     <td><%= @books_create.created_6days.count %></td>
     <td><%= @books_create.created_5days.count %></td>
     <td><%= @books_create.created_4days.count %></td>
     <td><%= @books_create.created_3days.count %></td>
     <td><%= @books_create.created_2days.count %></td>
     <td><%= @yesterday_book.count %></td>
     <td><%= @today_book.count %></td>
    </tr>
   </tbody>
  </table>
			<p>7日間の投稿数の比較</p>
			
	<canvas id="myChart" width="300" height="100"> </canvas>
		<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script> 
    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',                      
        data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [{
                label: "投稿した本の数",
                data: [<%= @books_create.created_6days.count %>, <%= @books_create.created_5days.count %>, <%= @books_create.created_4days.count %>, <%= @books_create.created_3days.count %>, <%= @books_create.created_2days.count %>, <%= @yesterday_book.count %>, <%= @today_book.count%>],
                backgroundColor: 'rgba(0, 80, 120, 1.0)',
                borderColor: 'rgba(0, 80, 120, 1.0)',
                fill: false,
                lineTension: 0.4
            }]
        },
    });
</script>


<%= form_with url: user_search_path(@user), method: :get, local: false do |f| %>
  <%= f.date_field :created_at %>　
  <%= f.submit '検索', class: 'btn btn-primary'  %>
<% end %>

<div id="search_result"> 
  <% if @search_book.present? %>
    <%= render 'search', search_book: @search_book %>　
  <% end %>
</div>

		</div>

	</div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/search_book.html.erb
<% if @book.errors.any? %>
				  <%= @book.errors.count %>error prohibited this book from being saved:
				  <ul>
				    <% @book.errors.full_messages.each do |message| %>
				      <li><%= message %></li>
				    <% end %>
				  </ul>
			<% end %>
<div class="container px-5 px-sm-0">

		<div class="row">



			<div class="col-md-3">
				<%= render 'users/user_show', user: @user %>
				<%= render 'books/book_new', book: @book %>
			</div>


		<div class="col-md-8 offset-md-1">

			<h1>Books</h1>
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
					  <th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th>Category</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
					<tr>
					  <td><%= link_to user_path(book.user) do %>
					  				<%= image_tag book.user.get_profile_image(40,40) %>
					  		<% end %>
					  </td>

						<td><%= link_to book_path(book.id) do %>
				          <%= book.title %>
				        <% end %>
				     </td>
						<td><%= book.body %></td>
						<td>
							<%= link_to book.category, search_book_path(keyword: book.category) %>
						</td>
						<td>
									          	<% if book.favorited_by?(current_user) %>
														    <p>
														      <%= link_to book_favorites_path(book.id), class: 'post-btn', method: :delete do %>
														        <i class="fa-solid fa-heart" style="color: red;"></i>
														        <span class='post-btn-text' style="color: red;"><%= book.favorites.count %></span>

														      <% end %>
														    </p>
														    <% else %>
														    <p>
														      <%= link_to book_favorites_path(book.id), class: 'post-btn', method: :post do %>
														        <i class="fa-solid fa-heart" style="color: blue;"></i>
														        <span class='post-btn-text' style="color: blue;"><%= book.favorites.count %></span>

														      <% end %>
														    </p>
													    <% end %>
				        </td>
				        <td>
				          <div id="star-rate<%= book.id%>"> </div>    
				          <script>
				            $('#star-rate<%= book.id %>').empty();
				            $('#star-rate<%= book.id%>').raty({
				              size      : 36,
				              starOff   : '<%= asset_path('star-off.png') %>',
				              starOn    : '<%= asset_path('star-on.png') %>',
				              starHalf  : '<%= asset_path('star-half.png') %>',
				              half      : true,
				              readOnly: true,
				              score: <%= book.star %>,
				            });
				          </script>
				          
								</td>
						    <td><p>コメント数：<%= book.book_comments.count %></p></td>
						    <td><%= l book.created_at %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

app/views/books/show.html.erb
<!--<%= alert %>-->

<div class="container px-5 px-sm-0">

		<div class="row">
						<div class="col-md-3">
							<%= render 'users/user_show', user: @user %>
							<%= render 'books/book_new', book: @newbook %>
						</div>


						<div class="col-md-8 offset-md-1">
  								<h2>Book detail</h2>
								  		<table class="table">
								  		  <tbody>
								  		  	<tr>
									          <td><%= image_tag @book.user.get_profile_image(40,40) %></br>
									          		<%= link_to @user.name, user_path(@user) %>
									          </td>

									          <td><%= @book.title %></td>
									          <td><%= @book.body %></td>
									          <td><%= @book.category%></td>
									          <td>
									          	<% if @book.favorited_by?(current_user) %>
														    <p>
														      <%= link_to book_favorites_path(@book.id), class: 'post-btn', method: :delete do %>
														        <i class="fa-solid fa-heart" style="color: red;"></i>
														        <span class='post-btn-text' style="color: red;"><%= @book.favorites.count %></span>

														      <% end %>
														    </p>
														    <% else %>
														    <p>
														      <%= link_to book_favorites_path(@book.id), class: 'post-btn', method: :post do %>
														        <i class="fa-solid fa-heart" style="color: blue;"></i>
														        <span class='post-btn-text' style="color: blue;"><%= @book.favorites.count %></span>

														      <% end %>
														    </p>
													    <% end %>
									          </td>
									          <td><p>コメント数：<%= @book.book_comments.count %></p></td>
									          <td><p>閲覧数: <%= @book.view_counts.count %></p></td>
									          <td>
									            <div id="star-rate<%= @book.id%>"></div>
									             <script>
									              $('#star-rate<%= @book.id %>').empty();
									              $('#star-rate<%= @book.id%>').raty({
									                 size      : 36,
									                 starOff   : '<%= asset_path('star-off.png') %>',
									                 starOn    : '<%= asset_path('star-on.png') %>',
									                 starHalf  : '<%= asset_path('star-half.png') %>',
									                 half      : true,
									                 readOnly: true,
									                 score: <%= @book.star %>,
									               });
									             </script>
          									</td>


									          <% if @book.user_id == current_user.id %>
									            <td><%= link_to "Edit", edit_book_path(@book), class: 'btn btn-success' %></td>
									            <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: "btn btn-danger" %></td>
									          <% end %>
									        </tr>
								      	</tbody>
								      </table>

								      <table>
								      	<tbody>
								      		<% @book.book_comments.each do |book_comment| %>
								  		  	<tr>
									      	<td>
									      		 	<p><%= image_tag book_comment.user.get_profile_image(50,50) %></p>
											    	<%=link_to user_path(book_comment.user.id) do %><%= book_comment.user.name %><% end %>
											    </td>

								      	  		<td>
								      	  			<%= book_comment.comment %>
								      	  		</td>

								      	  		<td>
								      	  			<% if book_comment.user == current_user %>
      															<%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: 'btn btn-sm btn-danger' %>
   														  <% end %>
								      	  		</td>

						                </tr>
						                <% end %>
								      </tbody>
						             </table>

						       		  <div class="form-group">
										  <%= form_with model: [@book, @book_comment] do |f| %>
										    <%= f.text_area :comment, rows: '5', class: 'form-control' %></br>
										    <%= f.submit "送信" %>
										  <% end %>
									  </div>



						</div>





				  <!--<p><%= image_tag @book.user.get_profile_image(100,100) %></p>-->
				  <!--<p><%= @book.user.name %></p>-->
				  <!--<p><%= @book.title %></p>-->
				  <!--<p><%= @book.body %></p>-->

				  <!--<% if @book.user == current_user %>-->
			   <!--      <%= link_to "Edit", edit_book_path(@book) %>-->
			  	<!--<% end %>-->


				  <!--<% if @book.user == current_user %>-->
			   <!--      <%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？" %>-->
			  	<!--<% end %>-->
	  </div>
</div>