config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  devise_for :users
  get 'home/about' => 'homes#about' , as: 'about'

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
    get "search", to: "users#search"
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  
  get "search_book" => "books#search_book"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	has_many :favorited_users, through: :favorites, source: :user

	has_many :view_counts, dependent: :destroy
	
	has_many :book_tags,dependent: :destroy
  has_many :tags,through: :book_tags

	scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
	scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
	scope :created_2days, -> { where(created_at: 2.days.ago.all_day) }
    scope :created_3days, -> { where(created_at: 3.days.ago.all_day) }
    scope :created_4days, -> { where(created_at: 4.days.ago.all_day) }
    scope :created_5days, -> { where(created_at: 5.days.ago.all_day) }
    scope :created_6days, -> { where(created_at: 6.days.ago.all_day) }

	scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
    scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  scope :star_count, -> {order(star: :desc)}
  
  def self.search(search_word)
    Book.where(['category LIKE ?', "%#{search_word}%"])
	end

	def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	
	belongs_to :user
  belongs_to :book
  
	validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	
	belongs_to :user
  belongs_to :book
	validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  
  has_one_attached :group_image
  
  def get_group_image(width, height)
	  unless group_image.attached?
	    file_path = Rails.root.join('app/assets/images/no_image.jpg')
	    group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
	  end
		group_image.variant(resize_to_limit: [width, height]).processed
	end


end

app/models/group_user.rb
class GroupUser < ApplicationRecord
	belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
belongs_to :following, class_name: "User"
belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :view_counts, dependent: :destroy
  has_many :group_users
  
  
  
  has_one_attached :profile_image
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  
  
  
   # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following
  # =======================================================================================
  
  

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end
  
  
  
  
def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end
  
  
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

              <li>
                <%= link_to "/users/#{current_user.id}", class: 'nav-link text-light post-btn' do %>
                <i class="fas fa-home"></i>
                <span class='post-btn-text'>Home</span>
                <% end %>
              </li>

              <li>
                <%= link_to users_path, class: 'nav-link text-light post-btn' do %>
                <i class="fas fa-users"></i>
                <span class='post-btn-text'>Users</span>
                <% end %>
              </li>

              <li>
                <%= link_to books_path, class: 'nav-link text-light post-btn' do %>
                <i class="fas fa-book-open"></i>
                <span class='post-btn-text'>Books</span>
                <% end %>
              </li>


              <li>
                <%= link_to destroy_user_session_path, class: 'nav-link text-light post-btn', method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>
                <span class='post-btn-text'>logout</span>
                <% end %>
              </li>
              <div class="search_form">
                <%= form_with url: search_book_path, local: true, method: :get do |f| %>
                  <%= f.text_field :keyword %>
                  <%= f.submit "検索", class: "btn btn-primary" %>
                <% end %>
              </div>
            <% else %>

              <li>
                <%= link_to root_path, class: 'nav-link text-light post-btn' do %>
                <i class="fas fa-home"></i>
                <span class='post-btn-text'>Home</span>
                <% end %>
              </li>

              <li>
                <%= link_to about_path, class: 'nav-link text-light post-btn' do %>
                <i class="fas fa-link"></i>
                <span class='post-btn-text'>About</span>
                <% end %>
              </li>

              <li>
                <%= link_to new_user_registration_path, class: 'nav-link text-light post-btn' do %>
                <i class="fas fa-user-plus"></i>
                <span class='post-btn-text'>sign up</span>
                <% end %>
              </li>

              <li>
                <%= link_to new_user_session_path, class: 'nav-link text-light post-btn' do %>
                <i class="fas fa-sign-in-alt"></i>
                <span class='post-btn-text'>login</span>
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

    <%= yield %>


    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>